server:
  port: 7600

spring:
  profiles:
    include: sharding

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    # http://192.168.200.1:8888/aaaa?a=b&c=d
    jdbcUrl: jdbc:mysql://192.168.6.100:3306/gmall_order?useSSL=false
    username: root
    password: 123456