server:
  port: 7500

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

app:
  threadpool:
    core-pool-size: 2
    maximum-pool-size: 4
    keep-alive-time: 600
    queue-size: 2000